name: Python CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests
    - name: Run Unit Tests
      run: pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Deploy to Streamlit
    - name: Deploy Streamlit App
      run: |
        pip install streamlit
        streamlit run app/main.py --server.port $PORT
